version: '{build}'
clone_depth: 1
environment:
  matrix:
    - VIM_URL: http://files.kaoriya.net/vim/vim74-kaoriya-win64.zip
    - VIM_URL: http://files.kaoriya.net/vim/2011/vim73-kaoriya-win64-20110306.zip
install:
  - 'cd %APPVEYOR_BUILD_FOLDER%'
  - 'appveyor DownloadFile %VIM_URL% -FileName %TEMP%\vim.zip'
  - '7z x -o%TEMP% %TEMP%\vim.zip > nul'
  - ps: $Env:THEMIS_VIM = (Get-ChildItem $Env:TEMP | Select-Object -First 1).FullName + '\vim.exe'

  - 'git -c advice.detachedHead=false clone https://github.com/Shougo/vimproc.vim --quiet --branch ver.9.2 --single-branch --depth 1 %TEMP%\vimproc'
  - 'git -c advice.detachedHead=false clone https://github.com/vim-jp/vital.vim --quiet --single-branch --depth 1 %TEMP%\vital'
  - 'git -c advice.detachedHead=false clone https://github.com/lambdalisue/vital-Vim-Python --quiet --single-branch --depth 1 %TEMP%\vital-Vim-Python'
  - 'appveyor DownloadFile https://github.com/Shougo/vimproc.vim/releases/download/ver.9.2/vimproc_win64.dll -FileName %TEMP%\vimproc\lib\vimproc_win64.dll'

  - 'git -c advice.detachedHead=false clone https://github.com/thinca/vim-themis --quiet --branch v1.5 --single-branch --depth 1 %TEMP%\vim-themis'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64'
build: off
test_script:
  - '%THEMIS_VIM% --version'
  - '%TEMP%\vim-themis\bin\themis.bat --runtimepath %TEMP%\vimproc --runtimepath %TEMP%\vital --runtimepath %TEMP%\vital-Vim-Python --reporter dot'
deploy: off
