version: '{build}'
clone_depth: 1
environment:
  matrix:
    - CONDITION: Official latest
    - CONDITION: Official 069
    - CONDITION: http://vim-jp.org/redirects/koron/vim-kaoriya/vim74/oldest/win32/
    - CONDITION: http://vim-jp.org/redirects/koron/vim-kaoriya/vim74/oldest/win64/
    - CONDITION: http://vim-jp.org/redirects/koron/vim-kaoriya/vim80/oldest/win32/
    - CONDITION: http://vim-jp.org/redirects/koron/vim-kaoriya/vim80/oldest/win64/
    - CONDITION: http://vim-jp.org/redirects/koron/vim-kaoriya/latest/win32/
    - CONDITION: http://vim-jp.org/redirects/koron/vim-kaoriya/latest/win64/
install:
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64'
  - 'git config --global user.name "Appveyor"'
  - 'git config --global user.email appveyor@example.com'
  - 'git clone -q --depth 1 --single-branch https://github.com/thinca/vim-themis %TEMP%\vim-themis'
  - 'git clone -q --depth 1 --single-branch https://github.com/vim-jp/vital.vim  %TEMP%\vital'
  - ps: .ci/install.ps1
test_script:
  - '%THEMIS_VIM% --version'
  - '%TEMP%\vim-themis\bin\themis.bat --reporter dot --runtimepath %TEMP%\vital'
build: off
deploy: off
